import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#EEF0F3",
  },
  containerCancelled: {
    backgroundColor: "#FAFAFA",
    borderColor: "#E5E7EB",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  dateBlock: {
    width: 60,
    alignItems: "center",
    justifyContent: "center",
    paddingRight: 14,
    borderRightWidth: 1,
    borderRightColor: "#EEF0F3",
  },
  dateWeekday: {
    fontSize: 10,
    color: "#9CA3AF",
    fontWeight: "500",
    textTransform: "capitalize",
    letterSpacing: 0.3,
  },
  dateDay: {
    fontSize: 24,
    color: "#111827",
    fontWeight: "600",
    lineHeight: 28,
    marginVertical: 2,
    fontVariant: ["tabular-nums"],
  },
  dateMonth: {
    fontSize: 10,
    color: "#9CA3AF",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  headerMain: {
    flex: 1,
    paddingHorizontal: 14,
  },
  timeRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
  },
  time: {
    fontSize: 20,
    color: "#111827",
    fontWeight: "600",
    letterSpacing: -0.4,
    fontVariant: ["tabular-nums"],
  },
  duration: {
    fontSize: 12,
    color: "#9CA3AF",
    fontWeight: "500",
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusLabel: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "500",
    letterSpacing: 0.2,
  },
  priceBlock: {
    alignItems: "flex-end",
    paddingLeft: 12,
  },
  priceLabel: {
    fontSize: 10,
    color: "#9CA3AF",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 2,
  },
  price: {
    fontSize: 14,
    color: "#111827",
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
  },
  divider: {
    height: 1,
    backgroundColor: "#F3F4F6",
    marginBottom: 16,
  },
  section: {
    marginBottom: 16,
  },
  sectionLabel: {
    fontSize: 10,
    color: "#9CA3AF",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  serviceName: {
    fontSize: 15,
    color: "#111827",
    fontWeight: "600",
    lineHeight: 21,
    letterSpacing: -0.2,
  },
  serviceDescription: {
    fontSize: 13,
    color: "#6B7280",
    lineHeight: 18,
    marginTop: 4,
  },
  peopleRow: {
    flexDirection: "row",
    gap: 24,
    marginBottom: 16,
  },
  personBlock: {
    flex: 1,
  },
  personHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  personId: {
    fontSize: 10,
    color: "#D1D5DB",
    fontWeight: "500",
    fontVariant: ["tabular-nums"],
  },
  personName: {
    fontSize: 14,
    color: "#111827",
    fontWeight: "600",
    lineHeight: 19,
  },
  personDetail: {
    fontSize: 12,
    color: "#9CA3AF",
    fontWeight: "400",
    marginTop: 2,
  },
  reasonText: {
    fontSize: 13,
    color: "#374151",
    lineHeight: 19,
    fontWeight: "400",
  },
  notesLabel: {
    fontSize: 10,
    color: "#9CA3AF",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginTop: 12,
    marginBottom: 6,
  },
  notesText: {
    fontSize: 12,
    color: "#6B7280",
    lineHeight: 18,
  },
  cancellationBlock: {
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    marginBottom: 14,
  },
  cancellationLabel: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "500",
  },
  cancellationReason: {
    fontSize: 13,
    color: "#374151",
    lineHeight: 19,
    marginTop: 4,
  },
  actionsRow: {
    marginTop: 4,
  },
  actionButton: {
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: "#0D9488",
    alignItems: "center",
  },
  actionText: {
    fontSize: 13,
    color: "#FFFFFF",
    fontWeight: "600",
    letterSpacing: 0.2,
  },
});
